apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: whis-db
parameters:
  - description: openshift namespace prefix
    name: NAMESPACE_PREFIX
    required: true
  - description: openshift namespace env name
    name: ENV
    required: true
  - description: The name given to the artifact
    name: NAME
    value: postgres-postgis
  - description: image tag for deployments
    name: TAG
    required: true
  - description: Image name
    name: IMAGENAME
    required: true
    value: postgres-postgis
objects:
  - kind: ImageStream
    apiVersion: image.openshift.io/v1
    metadata:
      name: postgres-postgis
    annotations:
      description: Database image stream
    spec:
      lookupPolicy:
        local: false
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: rhsm-ca
      namespace: ${NAMESPACE_PREFIX}-tools
    data:
      redhat-uep.pem: |
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: rhsm-conf
      namespace: ${NAMESPACE_PREFIX}-tools
      selfLink: /api/v1/namespaces/314c0c-tools/configmaps/rhsm-conf
    data:
      rhsm.conf: |
        [server]
        hostname = subscription.rhsm.redhat.com
        prefix = /subscription
        port = 443
        insecure = 0
        ssl_verify_depth = 3
        [rhsm]
        baseurl = https://cdn.redhat.com
        ca_cert_dir = /etc/rhsm/ca/
        repo_ca_cert = %(ca_cert_dir)sredhat-uep.pem
        productCertDir = /etc/pki/product
        entitlementCertDir = /etc/pki/entitlement
        consumerCertDir = /etc/pki/consumer
        manage_repos = 1
        full_refresh_on_yum = 0
        report_package_profile = 1
        pluginDir = /usr/share/rhsm-plugins
        pluginConfDir = /etc/rhsm/pluginconf.d
        auto_enable_yum_plugins = 1
        [rhsmcertd]
        certCheckInterval = 240
        autoAttachInterval = 1440
        splay = 1
        disable = 0
        [rhsmd]
        processTimeout = 300
        [logging]
        default_log_level = INFO
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: postgres-postgis
      namespace: ${NAMESPACE_PREFIX}-tools
      labels:
        app: whis
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: '${IMAGENAME}:latest'
      resources: {}
      successfulBuildsHistoryLimit: 2
      failedBuildsHistoryLimit: 1
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      postCommit: {}
      source:
        type: Git
        git:
          uri: 'https://github.com/bcgov/whis-db.git'
          ref: main
        secrets:
          - secret:
              name: etc-pki-entitlement
            destinationDir: etc-pki-entitlement
        configMaps:
          - configMap:
              name: rhsm-conf
            destinationDir: rhsm-conf
          - configMap:
              name: rhsm-ca
            destinationDir: rhsm-ca
      triggers:
      - type: ImageChange
      - type: ConfigChange
      - type: GitHub
        github:
          secretReference:
            name: whis-db-webhook
      runPolicy: SerialLatestOnly
