apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: whis-db
objects:
- kind: Secret
  apiVersion: v1
  metadata:
    name: whis    
  stringData:
    username: whis
    password: "${DATABASE_PASSWORD}"
- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: netapp-block-standard    
    name: whis-data  
  spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 10G
    volumeMode: Filesystem
- kind: DeploymentConfig
  apiVersion: apps.openshift.io/v1
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: >
        {"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","metadata":{"annotations":{},"labels":{"app":"whis-db"},"name":"whis-db","namespace":"0dff19-dev"},"spec":{"replicas":1,"selector":{"app":"whis-db","deploymentconfig":"whis-db"},"strategy":{"type":"Recreate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"whis-db","deploymentconfig":"whis-db"}},"spec":{"containers":[{"env":[{"name":"POSTGRESQL_PASSWORD","valueFrom":{"secretKeyRef":{"key":"password","name":"whis"}}},{"name":"POSTGRESQL_USER","valueFrom":{"secretKeyRef":{"key":"username","name":"whis"}}},{"name":"POSTGRESQL_DATABASE","value":"whis"}],"image":"
        ","imagePullPolicy":"Always","name":"whis-db","ports":[{"containerPort":5432,"protocol":"TCP"}],"resources":{"limits":{"memory":"2Gi"},"requests":{"memory":"1Gi"}},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/var/lib/pgsql/data","name":"volume-qvg1l"}]}],"dnsPolicy":"ClusterFirst","restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"terminationGracePeriodSeconds":30,"volumes":[{"name":"volume-qvg1l","persistentVolumeClaim":{"claimName":"whis-data"}}]}},"test":false,"triggers":[{"type":"ConfigChange"},{"imageChangeParams":{"automatic":true,"containerNames":["whis-db"],"from":{"kind":"ImageStreamTag","name":"postgres-postgis:latest","namespace":"0dff19-tools"}},"type":"ImageChange"}]}}
    name: whis-db    
    generation: 3
    labels:
      app: whis-db
  spec:
    strategy:
      type: Recreate
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      activeDeadlineSeconds: 21600
    triggers:
      - type: ConfigChange
      - type: ImageChange
        imageChangeParams:
          automatic: true
          containerNames:
            - whis-db
          from:
            kind: ImageStreamTag
            namespace: ${IMAGE_NAMESPACE}
            name: postgres-postgis:latest       
    replicas: 1
    revisionHistoryLimit: 10
    test: false
    selector:
      app: whis-db
      deploymentconfig: whis-db
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: whis-db
          deploymentconfig: whis-db
      spec:
        volumes:
          - name: volume-qvg1l
            persistentVolumeClaim:
              claimName: whis-data
        containers:
          - resources:
              limits:
                memory: 2Gi
              requests:
                memory: 1Gi
            terminationMessagePath: /dev/termination-log
            name: whis-db
            env:
              - name: POSTGRES_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: whis
                    key: password
              - name: POSTGRES_USER
                valueFrom:
                  secretKeyRef:
                    name: whis
                    key: username
              - name: POSTGRES_DATABASE
                value: whis
            ports:
              - containerPort: 5432
                protocol: TCP
            imagePullPolicy: Always
            volumeMounts:
              - name: volume-qvg1l
                mountPath: /var/lib/postgresql/data
            terminationMessagePolicy: File
        restartPolicy: Always
        terminationGracePeriodSeconds: 30
        dnsPolicy: ClusterFirst
        securityContext: {}
        schedulerName: default-scheduler 
- kind: Service
  apiVersion: v1
  metadata:
    name: whis-db
  spec:
    ports:
      - protocol: TCP
        port: 5432
        targetPort: 5432
    selector:
      app: whis-db
    type: ClusterIP
    sessionAffinity: None
parameters:
- name: NAME
  displayName: Name
  description: The name assigned to all of the resources defined in this template.
  required: true
  value: whis-ui
- name: APP_GROUP
  displayName: App Group
  description: Used to group components together.
  required: true
  value: whis
- name: SOURCE_IMAGE_NAME
  displayName: Source Image Name
  description: The name of the image to use for this resource.
  required: true
  value: whis-ui 
- name: IMAGE_NAMESPACE
  displayName: Image Namespace
  description: The namespace of the OpenShift project containing the imagestream for the application.
  required: true
  value: 314c0c-tools
- name: TAG_NAME
  displayName: Environment TAG name
  description: The TAG name for this environment, e.g., dev, test, prod
  required: true
  value: dev
- name: CPU_REQUEST
  displayName: CPU Request
  description: Starting amount of CPU the container can use.
  value: 10m
- name: CPU_LIMIT
  displayName: CPU Limit
  description: Maximum amount of CPU the container can use.
  value: 500m
- name: MEMORY_REQUEST
  displayName: Memory Request
  description: Starting amount of memory the container can use.
  value: 10Mi
- name: MEMORY_LIMIT
  displayName: Memory Limit
  description: Maximum amount of memory the container can use.
  value: 512Mi
- name: DATABASE_PASSWORD
  generate: expression
  from: "[a-zA-Z0-9]{16}"
  required: true
   
